### ISSUE TITLE
Page reloads completely upon refresh_token updates

### ISSUE THREAD

**Issue by ilyabo** [vercel/nextjs-subscription-payments#100]
I am trying to build an app based on this template and I noticed that my app's page reloads completely every now and then. It seems that it happens when Supabase is trying to refresh the auth token by fetching from this URL:
https://****.supabase.co/auth/v1/token?grant_type=refresh_token
But why does it lead to complete page reloads? Is it by design or am I doing something wrong?

Would appreciate any help on this issue!

**Comment by thorwebdev** [comment]
I haven't heard of this issue before, but I'm working on updating this example to utilise https://github.com/supabase-community/supabase-auth-helpers/blob/main/src/nextjs/README.md which will make things more robust in terms of auth strategy.

**Comment by ilyabo** [comment]
Thanks @thorwebdev! That's good to know. I will keep an eye on that.
