### ISSUE TITLE
deployed to vercel with the button in readme - build fails

### ISSUE THREAD

**Issue by bonesy512** [vercel/nextjs-subscription-payments#102]
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
--
10:50:21.530 | [object Object]
10:50:21.531 |  
10:50:21.531 | > Build error occurred
10:50:21.531 | Error: Export encountered errors on following paths:
10:50:21.531 | /
10:50:21.531 | at /vercel/path0/node_modules/next/dist/export/index.js:499:19
10:50:21.531 | at runMicrotasks (<anonymous>)
10:50:21.531 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
10:50:21.531 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
10:50:21.531 | at async /vercel/path0/node_modules/next/dist/build/index.js:1005:17
10:50:21.531 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
10:50:21.531 | at async /vercel/path0/node_modules/next/dist/build/index.js:879:13
10:50:21.531 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
10:50:21.531 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:82:25)
10:50:21.561 | error Command failed with exit code 1.
10:50:21.561 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:50:21.572 | Error: Command "yarn run build" exited with 1

**Comment by thorwebdev** [comment]
Can you check your project and see if all required env vars are set up? Also, can you try rebuilding the project to see if that works?

**Comment by thorwebdev** [comment]
Closing out due to inactivity. Feel free to reopen if you're still facing the issue.
