### ISSUE TITLE
Address the 400 error for api/auth/user

### ISSUE THREAD

**Issue by brentrobbins** [vercel/nextjs-subscription-payments#105]
I see this error on the demo site (an also my site using this setup) when you are not logged it. Any way to better handle this (possibly silencing it)?

![Screen Shot 2022-03-10 at 5 24 16 PM](https://user-images.githubusercontent.com/727491/157777992-88c81b70-fece-4a76-b962-a473cfd7fcaa.png)

**Comment by thorwebdev** [comment]
This has been fixed in https://github.com/supabase-community/supabase-auth-helpers/releases/tag/v1.2.2 and already been rolled into this demo 👍

**Comment by brentrobbins** [comment]
Thanks @thorwebdev! I really appreciate your help and development creating this super helpful resource.

So I updated updated the code and noticed another error. I created another issue [here](https://github.com/vercel/nextjs-subscription-payments/issues/108). Thanks again for all your help!
