### ISSUE TITLE
Failed to create project: Insert project failed: Get base price id failed: Product not found

### ISSUE THREAD

**Issue by mcm-gr** [vercel/nextjs-subscription-payments#106]
Hey guys.
I just started the Vercel deploy process. When I want to connect with supabase I get the error message described in the title. Have I overlooked something that I needed to do earlier? The error occurs exactly when I hit "Create project" (supabase pop up)

![image](https://user-images.githubusercontent.com/73694709/157850556-5044f067-ec12-4fae-b374-86bf22e57111.png)

**Comment by mobula9** [comment]
Exactly the same pb today for me.

**Comment by xedro98** [comment]
need help with this.

**Comment by thorwebdev** [comment]
Very sorry, this should have been fixed yesterday. Please reopen if it still persists for you. Thanks for reporting!
