### ISSUE TITLE
How to connect with existing Next.JS project?

### ISSUE THREAD

**Issue by pooriaarab** [vercel/nextjs-subscription-payments#107]
Hi, 

I want to know how we can use this with an existing deployed project. 

https://github.com/transitive-bullshit/nextjs-notion-starter-kit

Using that repo and want to setup my course using Notion. So, need to have payment gateway activated and membership/auth which seems this repo does well. 

Any recommendations on how to do it is appreciated. 

Also, how can we add gumroad as well instead of stripe?

**Comment by thorwebdev** [comment]
> Using that repo and want to setup my course using Notion. So, need to have payment gateway activated and membership/auth which seems this repo does well.
> 
> Any recommendations on how to do it is appreciated.

You can just pull out the code that you need.

> Also, how can we add gumroad as well instead of stripe?

Feel free to open a PR for it, or open an issue and see if someone is willing to add it.
