### ISSUE TITLE
Why sync Stripe resources to Postgres?

### ISSUE THREAD

**Issue by transitive-bullshit** [vercel/nextjs-subscription-payments#117]
I would've expected Stripe to remain the single source of truth for all billing models, with lightweight API accessors exposing them to the frontend, but this project seems to fully replicate them into Postgres.

Is it because we want to have Supabase as the only public API and handle all models uniformly on the frontend?

Just looking to understand the thought process and tradeoffs involved.

Thanks 🙏

**Comment by thorwebdev** [comment]
This has been discussed before, see https://github.com/vercel/nextjs-subscription-payments/issues/75#issuecomment-898239956

**Comment by transitive-bullshit** [comment]
Thanks for the explanation, Thor.
