### ISSUE TITLE
Display Metadata/Feature list in the frontend

### ISSUE THREAD

**Issue by onemarshall** [vercel/nextjs-subscription-payments#131]
Hi,

How do you display the metadata for each product in the front end? I want to display a list of features for each subscription product. And lastly, can Stripes 'Feature list' be used with this template?

Thanks

**Comment by leerob** [comment]
Hey there! You should be able to grab this information from Stripe (the template here doesn't have this added, but it should be possible with user code). Hope this helps!

**Comment by joshdumoulin** [comment]
> Hi,
> 
> How do you display the metadata for each product in the front end? I want to display a list of features for each subscription product. And lastly, can Stripes 'Feature list' be used with this template?
> 
> Thanks

I'm actually trying to do the same. Were you able to figure out how to do it?

**Comment by onemarshall** [comment]
No, sorry I was not able to figure it out.

**Comment by aamorozov** [comment]
Hi there, if someone stumbles upon this issue looking to add Stripe product features to this starter, here are the steps I took:
1. Create `features` column for products table, you can do it either in Supabase ui or Postgres schema file;
2. Update product fixtures with: `"features": [ { "name": "Unlimited customers" }, ...your features ]`;
3. Update supabase admin utility to add product features to supabase product table features column
4. Seed your fixtures into stripe and voila - you get a fancy features list
