### ISSUE TITLE
Small improvement to the Readme to avoid confusion

### ISSUE THREAD

**Issue by JPVRS** [vercel/nextjs-subscription-payments#143]
In the portion about creating and testing webhooks in Stripe, the reader is instructed to use their deployment URL as the endpoint. The URL listed under "deployment" in the Vercel dashboard doesn't work for this, which is a bit confusing. You have to use one of the URLs listed under "domains" instead. This is only confusing due to the fact that there's a URL in the Vercel dashboard that's explicitly labeled "deployment."

Additionally, the instructions to use the "Send test webhook" button in the Stripe dashboard can't be followed. That button doesn't currently exist in their UI. I was informed by someone on their support team that it's been temporarily removed due to technical issues. The only way to send a test webhook is through the CLI, which you can install locally or use online here:

https://stripe.com/docs/stripe-cli

The command is `stripe trigger product.created`

Clarification on these two points could help people avoid losing time on these steps. The instructions are great overall!

**Comment by thorwebdev** [comment]
Thanks for the feedback. I've removed the lines in question. Feel free to open a PR with further improvements :)
