### ISSUE TITLE
Convert to use App directory

### ISSUE THREAD

**Issue by BWBama85** [vercel/nextjs-subscription-payments#147]
Are there plans to convert this to use the new NextJS 13 app directory any time soon?

Has anyone successfully converted this over to 13?

**Comment by thorwebdev** [comment]
You should be able to upgrade this to use Next.js 13, however app directory is still in beta. We'll be working with the Vercel team to eventually move it over, but there isn't any rush. This approach is still good.

**Comment by darkomking** [comment]
It would be awesome to see this updated to use the app directory now that it's stable. The current supabase/app directory examples are very basic.
