### ISSUE TITLE
"Viewing test data" verbiage is out of date

### ISSUE THREAD

**Issue by adamzerner** [vercel/nextjs-subscription-payments#155]
> To start developing your SaaS application, we'll need to configure Stripe to handle test payments. For the following steps, make sure you have the "viewing test data" toggle switched to "on."

I think that "viewing test data" should probably instead say "Test mode"

<img width="1440" alt="Screenshot 2023-01-18 at 6 04 53 PM" src="https://user-images.githubusercontent.com/3144254/213338611-f720f1c1-ab1a-4a35-8c92-1fea6133afb6.png">

**Comment by leerob** [comment]
Thanks!

**Comment by adamzerner** [comment]
Thanks Lee!
