### ISSUE TITLE
What does the following code do?

### ISSUE THREAD

**Issue by TheBuilderJR** [vercel/nextjs-subscription-payments#160]
```
  const getSubscription = () =>
    supabase
      .from('subscriptions')
      .select('*, prices(*, products(*))')
      .in('status', ['trialing', 'active'])
      .single();
```

It's super unclear what the .select('*, prices(*, products(*))') means.

There is no price field on subscriptions, so what magic is going on? Google doesn't help me. Can we please add a comment?

**Comment by TimDev9492** [comment]
I think, this syntax is used to join the tables `prices` and `products` with the "parent" table respectively. For example, on every row of the `subscriptions` table, there is a `price_id` (foreign) key that's used to join that table with the `prices` table (primary key).

**Comment by thorwebdev** [comment]
Yes, correct, this is to pull in the content from foreign tables. You can find docs for it here: https://supabase.com/docs/reference/javascript/select
