### ISSUE TITLE
How does the subscription status change after the `current_period` ends?

### ISSUE THREAD

**Issue by TimDev9492** [vercel/nextjs-subscription-payments#163]
In the database `subscriptions`, every row has a property `status` that's used to query the currently active plans on the `/account` page. When you cancel a subscription through Stripe, the status doesn't get updated. Instead, the `cancel_at_period_end` property of the database entry in `subscriptions` gets changed to `true`. I was wondering if the `status` property changes "automatically" after the `current_period_end` date or if I have to implement that logic myself.

**Comment by thorwebdev** [comment]
The status is automatically updated via the webhook: https://github.com/vercel/nextjs-subscription-payments/blob/main/pages/api/webhooks.ts#L65-L89
