### ISSUE TITLE
Deleted products on Stripe still showing up

### ISSUE THREAD

**Issue by togume** [vercel/nextjs-subscription-payments#170]
Awesome template - it's amazing how quickly one can build these days.

Question: how do you delete products after they've been removed from Stripe? I removed a couple test products I had, but they're still showing up.

Does one delete them from the DB manually? Something else?

Thanks!

**Comment by togume** [comment]
Update: manually deleting them from Supabase (pricing & products) does the trick.

Should this be done via webhook?

**Comment by MaximusMcCann** [comment]
The webhook appears to error on delete :(

**Comment by kevinkatzke** [comment]
@togume The current implementation of the webhook in `app/webhook/route.ts` does not support the `product.deleted` event that is sent by Stripe. With the way this project is currently implemented the only way to delete Stipe product is to manually delete them from the Supabase DB. Adding support for more Stripe events would be great!

**Comment by chriscarrollsmith** [comment]
Opened a PR to fix this issue:

https://github.com/vercel/nextjs-subscription-payments/pull/271

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278

**Comment by belugawhale3** [comment]
I'm still seeing this issue. Anyone else?

**Comment by belugawhale3** [comment]
Never mind it was a env var issue
