### ISSUE TITLE
generated tables are owned by supabase_admin and therefore not editable

### ISSUE THREAD

**Issue by thosmos** [vercel/nextjs-subscription-payments#172]
When I generated a Supabase project using Vercel's automated deployment, and then attempted to make any changes to the tables or policies created by this integration, I got an error about not being the owner.  I tried running the deployment a second time and got the same result.  

<img width="382" alt="Screen Shot 2023-03-18 at 9 49 04 AM" src="https://user-images.githubusercontent.com/621286/226131789-64bb38fa-4067-4ebe-b057-db86459dfb29.png">

It looks like the problem is that the tables are owned by the `supabase_admin` user instead of `postgres` which is the new current default.  Here's an example showing the ownership of the tables as contrasted with the `dashtest` table that was created using Supabase's dashboard:

```
postgres=> \dt
                List of relations
 Schema |     Name      | Type  |     Owner      
--------+---------------+-------+----------------
 public | customers     | table | supabase_admin
 public | dashtest      | table | postgres
 public | prices        | table | supabase_admin
 public | products      | table | supabase_admin
 public | subscriptions | table | supabase_admin
 public | users         | table | supabase_admin
(6 rows)
```

I created a new Supabase project and ran the schema.sql file directly in the dashboard SQL Editor and the tables were owned by `postgres`:

```
postgres=> \dt
             List of relations
 Schema |     Name      | Type  |  Owner   
--------+---------------+-------+----------
 public | customers     | table | postgres
 public | prices        | table | postgres
 public | products      | table | postgres
 public | subscriptions | table | postgres
 public | users         | table | postgres
(5 rows)
```

So this appears to be a problem with how the schema.sql file is run when doing the automated deployment.

**Comment by btahir** [comment]
Just ran into this issue :(

Wth - was working fine before. Any magic SQL we can run in the console to fix this?

**Comment by btahir** [comment]
I tried...didn't work. Ended up just creating a new table.

**Comment by devalsysoft** [comment]
Or connect with dbeaver or pgAdmin and edit owners.

**Comment by thorwebdev** [comment]
Thanks for reporting this, we're currently looking into it.

**Comment by thorwebdev** [comment]
This has now been fixed. Unfortunately you will need to start over to get this set up correctly, sorry about that!

**Comment by jinalex** [comment]
Deployed a new project over the weekend and all my tables are still owned by supabase_admin btw

**Comment by fabianuribe** [comment]
+1 . `supabase_admin` is still the owner of the tables for my project launched on Mar 30, 2023 (after the bug was closed)

cc/ @thorwebdev

**Comment by thorwebdev** [comment]
Reopening and investigating, thanks for reporting!

**Comment by thorwebdev** [comment]
Sorry about this, there was a regression in our Vercel Deploy integration that changed the role of the setup SQL. This has now been fixed again and should work as expected for new installations.
