### ISSUE TITLE
Unable to create new project with `deploy`

### ISSUE THREAD

**Issue by carbone-stone** [vercel/nextjs-subscription-payments#187]
Contrary to the previous seamless integrations, I am no longer able to create a clone of this repo with `deploy` button and get vercel project deployed. Are we aware of this issue?

I have tried to reproduce this with a new github account, to make sure it's not due to my already existing project.

How can we debug this issue?

Thank you for the awesome product!

**Comment by vimota** [comment]
Having the same issue it fails with:

```


Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
--


<span>    at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:177:21)</span>
```

**Comment by vimota** [comment]
Ah I missed these lines:

```
Once the project has deployed, continue with the configuration steps below.

The initial build will fail due to missing Stripe environment variables. After configuring Stripe, redeploy the application.
```

Searching for the Supabase integration and setting up it fixed the deploy.
