### ISSUE TITLE
Why Supabase and not just PG?

### ISSUE THREAD

**Issue by gamedevsam** [vercel/nextjs-subscription-payments#205]
This is great, but for several reasons (including cost), I decided to roll my own PG instances.

I looked at the migrations and seems like just about everything is compatible with plain old postgres except the RLS which uses a function Supabase injects into their PG instances: `auth.uid()`

Do you have any advice on how to implement the same functionality without relying on Supabase?

PS:

Any example you guys offer with plain PG would work great with Supabase, just saying.

**Comment by lms11** [comment]
AFAIK, Supabase is open-source so you can deploy your own instance as well. They also provide a backend layer that makes this project nearly trivial to implement. On the other hand, doing all of that on top of Postgres directly would be much more time consuming.

PS: I'm not a maintainer on this project.

**Comment by thorwebdev** [comment]
I'll leave this one for @leerob and team to answer as I'm highly biased as a Supabase employee. That being said, the big benefit of using Supabase here is the connectedness of Auth with the DB using row level security policies, making it easier to manage the business logic of who can see what data.

**Comment by leerob** [comment]
A few thoughts:

- Supabase is open-source
- This repo could be easily swapped out to use `pg` if you prefer, including your own auth provider
