### ISSUE TITLE
Update docs to include migration guide/notes for Next.js 13 app dir changes to this project

### ISSUE THREAD

**Issue by i-bsd** [vercel/nextjs-subscription-payments#210]
We built out an app using this starter, about to release it, then Next.js 13 app dir dropped. Now we need to refactor. 

Any chance of getting some migration notes/steps for this project added to the README from the page route version to the app dir version?

Specifically as it relates to Supabase (localStorage to cookies and so on).

**Comment by thorwebdev** [comment]
There's no rush for you to change to app directory. The pages directory is still very much supported in Next.js 13 and you might actually be better off sticking with it for a while longer.

No plans for a migration guide specifically, but you can review the PR diff: https://github.com/vercel/nextjs-subscription-payments/pull/183/files
