### ISSUE TITLE
Stripe error with webhooks

### ISSUE THREAD

**Issue by TommyDong1998** [vercel/nextjs-subscription-payments#224]
Previously the webhooks were working but I noticed this week that the webhooks are all giving 500 errors. I deleted an product from stripe console and also added one. They all give the same error: 
 
[POST]
/api/webhooks

----------------------------------------------------------------------------------------------------------------------------
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
- error TypeError: Cannot read properties of undefined (reading 'headers')
    at /var/task/.next/server/chunks/501.js:3897:61
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by TommyDong1998** [comment]
Update: Found out that the env variable STRIPE_WEBHOOK_SECRET_LIVE is now STRIPE_WEBHOOK_SECRET 😅

The error came from 
`if (!sig || !webhookSecret) return;`
  
 Lets change that to 
```
 if (!sig || !webhookSecret) {
      return new Response(`Missing signature or webhook secret`, {
        status: 500
      });
    }
```
so that it is more understandable

**Comment by espinozahector** [comment]
@TommyDong1998 Were you able to get this resolved? I validated the .env variable and I still receive a 500 error. 
I believe it is more of an issue with the stripe signature

**Comment by kevinkatzke** [comment]
@espinozahector Renaming the environment variable `STRIPE_WEBHOOK_SECRET_LIVE` to `STRIPE_WEBHOOK_SECRET` in the Vercel settings of your project fixes the error. Don't forget to redeploy the latest deployment from the Vercel Dashboard for these changes to take effect.

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
