### ISSUE TITLE
Incorrectly converting stripe timestamps to DateTimes

### ISSUE THREAD

**Issue by ericallam** [vercel/nextjs-subscription-payments#225]
Currently timestamps are hydrated to Dates using the following function:

```ts
export const toDateTime = (secs: number) => {
  var t = new Date('1970-01-01T00:30:00Z'); // Unix epoch start.
  t.setSeconds(secs);
  return t;
};
```

A couple issues here:

- Unix epoch is starting 30 minutes late
- You could just do `new Date(secs * 1000)`

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
