### ISSUE TITLE
Middleware called on all request, no matcher set

### ISSUE THREAD

**Issue by mozeryansky** [vercel/nextjs-subscription-payments#227]
Right now the [`middleware.ts`](https://github.com/vercel/nextjs-subscription-payments/blob/main/middleware.ts#L7) will be called for every request. I believe it's setup as an example for supabase, but I'm unsure if it's either incomplete or just unused.

I think it should at least include the recommended matcher from the [nextjs docs](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher):
```
export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```

**Comment by chriscarrollsmith** [comment]
> Right now the [`middleware.ts`](https://github.com/vercel/nextjs-subscription-payments/blob/main/middleware.ts#L7) will be called for every request. I believe it's setup as an example for supabase, but I'm unsure if it's either incomplete or just unused.
> 
> I think it should at least include the recommended matcher from the [nextjs docs](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher):
> 
> ```
> export const config = {
>   matcher: [
>     /*
>      * Match all request paths except for the ones starting with:
>      * - api (API routes)
>      * - _next/static (static files)
>      * - _next/image (image optimization files)
>      * - favicon.ico (favicon file)
>      */
>     '/((?!api|_next/static|_next/image|favicon.ico).*)',
>   ],
> }
> ```

I don't think you'll want to exclude API routes from the middleware, since those use a server-side authentication client, and managing such sessions is the purpose of the middleware.

**Comment by chriscarrollsmith** [comment]
This issue has been resolved and can be closed.
