### ISSUE TITLE
Deprecated! Supabase Auth Helpers

### ISSUE THREAD

**Issue by guylepage3** [vercel/nextjs-subscription-payments#237]
> This project is now out of date. 

Supabase deprecated the Auth Helpers used in this project and now requires quite a bit of refactoring / restructuring.

**Deprecated helpers currently used in this app**

- [`createBrowserSupabaseClient`](https://supabase.github.io/auth-helpers/modules/nextjs_src.html#createBrowserSupabaseClient)
- [`createMiddlewareSupabaseClient`](https://supabase.github.io/auth-helpers/modules/nextjs_src.html#createMiddlewareSupabaseClient)
- [`createServerSupabaseClient`](https://supabase.github.io/auth-helpers/modules/nextjs_src.html#createServerSupabaseClient)

**New Helpers**

- [Client Components](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#client-components) — createClientComponentClient
- [Server Components](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#server-components) — createServerComponentClient
- [Server Actions](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#server-actions) — createServerActionClient
- [Route Handlers](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#route-handlers) — createRouteHandlerClient
- [Middleware](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#middleware) — createMiddlewareClient

Secondly, since Supabase Auth UI is in `beta` and only [offers nominal views](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui#supported-views), the auth functionality is not usable as of yet. Users cannot update passwords, email addresses, etc. Leaving the developer to build out Auth from scratch. Supabase is great but this project should build out Supabase Auth views on its own.

**Comment by MincePie** [comment]
is there an example of how to do this?

**Comment by guylepage3** [comment]
There are links to the documentation on how to use the helpers and there is this very light weight run through here: https://supabase.com/docs/guides/auth/auth-helpers/nextjs

**Comment by nate-oo** [comment]
Hi @guylepage3

I was looking at this and trying to figure out what the update process might be like. However, I don't see the old deprecated function names like you are referring to in the code within the repo.

Unless I am missing something (I could be...I am relatively new to web development), it looks like all the new functions names are being used throughout the repo.  

Could you point out some lines of code and file names that you are referring to that use the deprecated functions?

**Comment by nate-oo** [comment]
@guylepage3 isn't that just the custom name of the constant though? 

That exports a constant that is a custom defined function with the name of `createServerSupabaseClient` for use throughout the application doesn't it? 

The actual nextjs helper used is `createServerComponentClient` like you see here in that file:
`import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';`

and here:
`createServerComponentClient<Database>({ cookies })`

I could be wrong as I am newer to web development.  Am I missing something?

**Comment by guylepage3** [comment]
Feel free to read up on Supabase in their docs as well. You'll quickly realize that the implementations vary considerably.

**Comment by nate-oo** [comment]
Thanks @guylepage3.  I guess I am confusing myself :).  Sorry I'm new trying to figure this out.

Isn't everything that has the words `SupabaseClient` in this repo actually just names of `constants` and not the actual imported `helpers`?

**Comment by guylepage3** [comment]
Nope. But `SupabaseClient` is a constant. Someone decided it was a good idea to name one of the constants part of the name of the helpers. Just to confuse everyone. Lol.

I thought I could save you some time but just do 3 searches instead of just one.

Search for;

- `createBrowserSupabaseClient`
- `createMiddlewareSupabaseClient`
- `createServerSupabaseClient`

**Comment by nate-oo** [comment]
Thanks @guylepage3.  I am still confused lol.  I'll have to do more research to figure this out for myself

**Comment by guylepage3** [comment]
Lmao. Please read ALL the links I created in my initial comment.

I provided all the links to the deprecated posts from Supabase.

It's not confusing at all.

**Comment by micheltucker** [comment]
> @micheltucker do what you will. But unless someone has completed the change, then it's incomplete. Zero confusion actually.

Would you mind sharing one diff of your proposed change?

**Comment by guylepage3** [comment]
It's provided by the supabase folks.. Please re-read. Thx
