### ISSUE TITLE
Auth not working after deployment to Vercel

### ISSUE THREAD

**Issue by Shivansh-yadav13** [vercel/nextjs-subscription-payments#246]
I have followed the Readme file and deployed my app
but there is 1 issue, 
on my localhost:3000 authentication works perfectly but after deploying it to vercel
it does not work and the console shows this

```
https://mzwpeqplxjiupysnwteo.supabase.co/auth/v1/token?grant_type=pkce 401
```

after making auth request

Failed to load resource: the server responded with a status of 401 ()

I have a failed request in the logs could that be the reason

![promethus](https://github.com/vercel/nextjs-subscription-payments/assets/87603425/1100bd16-6656-4211-9f3d-fd2cbed9cf4d)

**Comment by Shivansh-yadav13** [comment]
There was some issue with my ENV variable 😑

**Comment by selalipop** [comment]
What issue?
