### ISSUE TITLE
"Promise<Response \| undefined>" is not a valid POST return type

### ISSUE THREAD

**Issue by denisprado** [vercel/nextjs-subscription-payments#248]
I am getting the follow error when deploying to vercel:

Failed to compile.
16:09:50.139 | src/app/api/webhooks/route.ts
16:09:50.140 | Type error: Route "src/app/api/webhooks/route.ts" has an invalid export:
16:09:50.140 | "Promise<Response \| undefined>" is not a valid POST return type:
16:09:50.140 | Expected "Response \| Promise<Response>", got "Promise<Response \| undefined>".
16:09:50.140 | Expected "Promise<Response>", got "Promise<Response \| undefined>".
16:09:50.140 | Expected "Response", got "Response \| undefined".
16:09:50.140 | Expected "Response", got "undefined".
`

but I have not changed this file. Any one guess what is happening?

**Comment by jonkurtis** [comment]
Same. I have not made any changes and now getting this error in build output.

**Comment by jonkurtis** [comment]
In the webhook this line is the problem:
`if (!sig || !webhookSecret) return`
You actually need to throw an error here so that the error will be caught and a Response can be returned. 
Like this:
`if (!sig || !webhookSecret) throw new Error("Missing Stripe Signature or Webhook Secret!")`

**Comment by Shivansh-yadav13** [comment]
I'm facing the same issue,
I tried to replace `ReturnType<MaybeField<TEntry, 'POST'>>` with `Response | Promise<Response>`

but when I run `npm run build` it switch back to `ReturnType<MaybeField<TEntry, 'POST'>>`

error

```
Type '{ __tag__: "POST"; __return_type__: Promise<Response | undefined>; }' does not satisfy the constraint '{ __tag__: "POST"; __return_type__: Response | Promise<Response>; }'.
  Types of property '__return_type__' are incompatible.
    Type 'Promise<Response | undefined>' is not assignable to type 'Response | Promise<Response>'.
      Type 'Promise<Response | undefined>' is not assignable to type 'Promise<Response>'.
        Type 'Response | undefined' is not assignable to type 'Response'.
          Type 'undefined' is not assignable to type 'Response'.
```

**Comment by Shivansh-yadav13** [comment]
Thanks @jonkurtis it solved the issue 👍

**Comment by chriscarrollsmith** [comment]
Opened a PR to fix this issue.

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
