### ISSUE TITLE
Subscribe Button

### ISSUE THREAD

**Issue by jarrodlatshaw** [vercel/nextjs-subscription-payments#252]
Not so much an issue as it is a question. Ive gotten everything to work, I was curious about the subscribe button though. Does that only become activated if you upgrade your stripe account or something? Might be a dumb question but I appreciate anyone's guidance... I was trying to look through the files to understand the functionality there but I'm not entirely sure if I'm missing something obvious...

**Comment by thorwebdev** [comment]
No, the subscribe button should work as long as the user is logged in.
