### ISSUE TITLE
Stripe Subscription Plans Not Displaying on Vercel-Deployed Site

### ISSUE THREAD

**Issue by lingxuahu** [vercel/nextjs-subscription-payments#259]
I've deployed a Stripe starter code to Vercel, but I'm encountering issues with displaying available subscription plans. The site shows a message stating, 'No subscription pricing plans found. Create them in your Stripe Dashboard.' The project is hosted at https://subscription-starter-chi-two.vercel.app/

I've already configured several products and pricing plans in Stripe's test mode, and I've also correctly set up all the required keys (public, private, and webhook) in Vercel. Despite this, there are no log errors to indicate what might be wrong. I also redeployed a few times without luck.

Additionally, when I manually create a new product or pricing plan in Stripe, I receive a webhook error that says, 'No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe?' I'm not sure if this error is related to the issue of not displaying existing plans, as the problem existed even before adding new products or pricing.

Could anyone help me identify the potential causes and suggest debugging steps? Your assistance would be greatly appreciated.

**Comment by lingxuahu** [comment]
Working now after updating the webhook key and adding a new pricing plan and redeployment.

**Comment by lingxuahu** [comment]
Working now after updating the webhook key and adding a new pricing plan and redeployment.

**Comment by jayzopps** [comment]
@lingxuahu how'd you get it to work? Is the webhook key in the initial setup wrong? I have the webhook secret but nothing works
