### ISSUE TITLE
Add stripe-cli fixtures for creating products & prices

### ISSUE THREAD

**Issue by thorwebdev** [vercel/nextjs-subscription-payments#26]
# Feature request

## Is your feature request related to a problem? Please describe.

When you deploy the starter it doesn't have any products and prices because the Stripe account doesn't have any.

## Describe the solution you'd like

Create a fixture json file to bootstrap some products & prices: https://stripe.com/docs/cli/fixtures

**Comment by needcaffeine** [comment]
@thorwebdev @leerob Does this commit need anything more to get merged in?
