### ISSUE TITLE
Can't update account information on Oauth connected account

### ISSUE THREAD

**Issue by geuis** [vercel/nextjs-subscription-payments#265]
Just getting this all setup for the first time. I have the app up and running.

I just created an Oauth app for Github and was able to sign in. However, when I got to Account I can't update the name or email address. The text fields can be typed in, but the "Update Name" and "Update Email" buttons are disabled.

I did a quick scan through Supabase but I didn't find any settings that seemed to address this. 

Any idea how to fix this?

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
