### ISSUE TITLE
OAuth with Supabase Auth UI doesn't work on chrome browser

### ISSUE THREAD

**Issue by absolutegravitas** [vercel/nextjs-subscription-payments#267]
as the title says -- attempt sign in with provider and error 500 on client side received
on firefox this works and is let through

**Comment by rayne1066** [comment]
I am having the same issue. Works in edge, but not chrome

**Comment by rayne1066** [comment]
This maybe a cookie issue. If you have not deleted old cookies, it could be causing authentication errors.

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
