### ISSUE TITLE
Empty NEXT_PUBLIC_SITE_URL env var breaks checkout in local testing

### ISSUE THREAD

**Issue by chriscarrollsmith** [vercel/nextjs-subscription-payments#269]
The example .env.local file contains this text:

```
# Update this with your stable site URL only for the production environment.
NEXT_PUBLIC_SITE_URL=
```

If the user leaves this variable empty rather than deleting it, the template fails to create a checkout session during local testing. That's because getURL in 'helpers.ts' is only using the localhost fallback when NEXT_PUBLIC_SITE_URL is non-existent, not when it's empty.

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
