### ISSUE TITLE
Account Details Update Buttons

### ISSUE THREAD

**Issue by andrewshrout** [vercel/nextjs-subscription-payments#28]
# Feature request

The account details page is set up to imply that you can update your account. Entry forms and buttons that actually update these things in the database would be nice.

## Describe the solution you'd like

An example of updating the name (so I can implement the email update), or full implementation by default. 

## Describe alternatives you've considered

Currently going to try to write it myself based on the handleSignUp logic.

## Additional context

Upon a local implementation and initial signup - the Full Name didn't get added to the database. When I went to manually do it in account details, there's no buttons - thus the request.

Thanks for the starter and the project. Solves some serious headaches and is very very cool.

**Comment by reesef** [comment]
@andrewshrout I ran into this as well. Did you end up adding this to the account page or modifying handleSignUp to update full_name in the DB when signing up?

**Comment by audrow** [comment]
You can add this yourself by using the Supabase client with the update method. For example, you could call a method like this when an input field is changed.

```typescript
  async function updateUser({fullName}: {fullName: string}) {
    setLoading(true)
    try {
      const { error } = await supabase.from('users').update({full_name: fullName}).match({id: user.id});
      if (error) {
        throw error
      }
    } catch (error) {
      if (error) return alert((error as Error).message);
    }
  }
```

However, the example uses React contexts and I'm not sure how to nicely work with contexts and Supabase. Any thoughts or advice would be appreciated.
