### ISSUE TITLE
Issue with trial period setting

### ISSUE THREAD

**Issue by Sylvesterx1** [vercel/nextjs-subscription-payments#283]
Currently I think not possible set trial period for product  directly in Stripe Panel. They said now need to provide trial period in params during subscription.

In table supabase, i set trial period to 7 days. Now when I try subscribe this product from app, looks like still try charge cash imitidaly, but should after 7 days.  

![image](https://github.com/vercel/nextjs-subscription-payments/assets/35328055/09e38909-71bc-4370-a2e3-2dcba6a3dc12)
![image](https://github.com/vercel/nextjs-subscription-payments/assets/35328055/22977e80-b064-42f6-8e94-2b673c2f8c93)

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
