### ISSUE TITLE
Supabase + Vercel Deploy Button loading forever

### ISSUE THREAD

**Issue by LeoLin4258** [vercel/nextjs-subscription-payments#287]
I attempted to deploy this project using the Vercel Deploy Button, and after following the instructions to click on adding Supabase, I got stuck on this page. I've been trying for several days, but the result is the same.

![3666afe995cca3797fb0e7f635f815f](https://github.com/vercel/nextjs-subscription-payments/assets/146353430/875f2365-ef01-467b-b259-3381a2c0aff8)

**Comment by nozma-knows** [comment]
Any updates on this? I'm experiencing the same issue. I've tried with multiple apps that are using the Supabase integration and am experiencing this problem for all of them.

**Comment by shredEngineer** [comment]
Yup, had the same problem. I just gave up and did the integration manually. Somehow it worked.

**Comment by LeoLin4258** [comment]
https://github.com/orgs/vercel/discussions/5589
