### ISSUE TITLE
Breaking Change by Stripe: Example needs overhaul

### ISSUE THREAD

**Issue by guylepage3** [vercel/nextjs-subscription-payments#290]
So, It looks as though, Stripe made a leap forward with their service and as a result there is a breaking change if someone would like to update Stripe beyond `stripe` `v12.6.0` and move on to `stripe` `v14.15.0`.

It looks as though the folks at Vercel did not create this tutorial as well. It looks like the folks at Supabase started it and therefore I don't know if anyone at Vercel will update this tutorial.

Would be helpful though.

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/278
