### ISSUE TITLE
Cannot setup supabase local instance

### ISSUE THREAD

**Issue by belugawhale3** [vercel/nextjs-subscription-payments#300]
When I run the command:
npm run supabase:start

Throw this error:
 open supabase\config.toml: The system cannot find the file specified.

I've made sure that docker is running and I was able to make it this far in the READme without errors

**Comment by masakinihirota** [comment]
You must run the `supabase init` command to generate config.toml.
For more information, see
Local Development | Supabase Docs
https://supabase.com/docs/guides/cli/local-development

**Comment by belugawhale3** [comment]
Yep that fixed it, that step should probably be added to the docs
