### ISSUE TITLE
pnpm supabase:pull and pnpm supabase:push missing "db"

### ISSUE THREAD

**Issue by Tera-Nuovo** [vercel/nextjs-subscription-payments#315]
In the package.json the pull and push commands says:

"supabase:push": "npx supabase push",
"supabase:pull": "npx supabase pull"
   
But that doesn't work it seems it should have db added to it like this:

"supabase:push": "npx supabase db push",
"supabase:pull": "npx supabase db pull"

**Comment by k-thornton** [comment]
The PR referenced above fixes this really nicely.  I'd merge it in!

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-subscription-payments/pull/329
