### ISSUE TITLE
Vercel Deployment fails due to i18n incompatibility

### ISSUE THREAD

**Issue by geordidearns** [vercel/nextjs-subscription-payments#32]
# Bug report

## Describe the bug

While trying to deploy my app on vercel I encountered a problem that caused the deployment to crash. I received this error in the deployment log from Vercel:

`

21:40:23.338 | info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
-- | --
21:40:23.339 | Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
21:40:23.339 | at exportApp (/vercel/workpath0/node_modules/next/dist/export/index.js:14:322)
21:40:23.352 | error Command failed with exit code 1.

`

NOTE: I did have to change the 'Framework Preset' under 'Build & Development Settings' to get it to deploy without it showing the directory in the first place (https://vercel.com/docs/directory-listing), so could be related to this - But that in itself was a blocker to deploying :) 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the repository
2. Follow the integrations steps with Vercel
3. Push a branch to master
4. See a directory (not the served site)
5. Change the 'Framework Preset' to Next.js
6. Try push to master again
7. Receive the above error
8. Remove the i18n in the next.config file
9. Re-deploy - great success (Although no i18n config 🤔 )

## Expected behavior

- I wouldn't have to change the config on Vercel to Next.js (It should pick up it be default right?)
- I wouldn't have to remove the i18n config to get a successful deploy

## System information

- OS: MacOS Big Sur
- Google Chrome
- Yarn package manager

## Additional context

This is perhaps a documentation thing, more than technical - But for a newbie to Next.js, and Vercel it was a little tricky - I'm happy to go through the flow again (re-clone a repo etc) if needed

Thanks for the fantastic template! 🎉

**Comment by leerob** [comment]
We can probably remove `next.config.js` entirely, that i18n bit isn't necessary 👍

**Comment by geordidearns** [comment]
Okay great @leerob - I can make a PR for it over the next day if no one takes care of it before then :)

**Comment by leerob** [comment]
Fixed https://github.com/vercel/nextjs-subscription-payments/commit/da3e155b64a5a17d0346eefab1f43c8026885138.
