### ISSUE TITLE
Deprecating `auth-helpers`

### ISSUE THREAD

**Issue by guylepage3** [vercel/nextjs-subscription-payments#326]
It looks as though a while back someone started to attempt to refactor the starter template to use a client instead of `auth-helpers` as recommended by Supabase but they seemed to have either failed or did not finish.

> Commit link —› https://github.com/vercel/nextjs-subscription-payments/commit/a138bf79becca3f6abf40f04138c2eecac50a5f2

Supabase `"generally recommends"` using the new `@supabase/ssr` package.
https://supabase.com/docs/guides/auth/auth-helpers

I was wondering if someone was planning on updating this at some point? I have taken a stab at it and even used ChatGPT to give it a go and its quite an undertaking. Having said that, I feel it would be worth it at some point. 

The commit that I've referenced above was pushed Feb 12, 2024

Any update on this would be helpful.

**Comment by oliviermills** [comment]
The code base fully uses @supabase/ssr already, the folder is just called auth-helpers.

**Comment by guylepage3** [comment]
Wow. My bad. I thought I saw `auth-helpers` in `package.json`.
