### ISSUE TITLE
Question: Passing supabase to query functions?

### ISSUE THREAD

**Issue by stevengrimaldo** [vercel/nextjs-subscription-payments#354]
Just out of curiosity how come you're importing the supabase createClient() functions on the pages and passing supabase to the query functions as an argument rather than just importing the createClient methods directly into the queries file?

Wondering if this was just a matter of preference or if there was a real technical reason as to one way or the other.

**Comment by floatrx** [comment]
> Just out of curiosity how come you're importing the supabase createClient() functions on the pages and passing supabase to the query functions as an argument rather than just importing the createClient methods directly into the queries file?
> 
> Wondering if this was just a matter of preference or if there was a real technical reason as to one way or the other.

dependency injection
