### ISSUE TITLE
Prevent flash of footer on the account page

### ISSUE THREAD

**Issue by leerob** [vercel/nextjs-subscription-payments#45]
When loading the account page, there's a small flash of the footer before the page renders

https://user-images.githubusercontent.com/9113740/105638688-a6d42580-5e39-11eb-9987-ed75bf62638e.mp4

**Comment by ingokpp** [comment]
Maybe this is because of the client side user check + redirect?

**Comment by tedspare** [comment]
Good eye! In account.js on line 30, unauthenticated users are redirected to `/signin`. Surely enough, the video shows that URL briefly.
> Sent from [ <img width='15' alt='Neat.run' src='https://user-images.githubusercontent.com/36117635/130461991-31ea8e65-5ef2-44c0-994e-80edbbb4c064.png'>](https://neat.run)

**Comment by leerob** [comment]
This has been fixed!
