### ISSUE TITLE
Improve login page UI

### ISSUE THREAD

**Issue by leerob** [vercel/nextjs-subscription-payments#48]
- Submit button should not be disabled
- _Or_ shouldn't be italic
- Left input spacing for the input is a bit too much

**Comment by needcaffeine** [comment]
We could use https://github.com/supabase/ui directly and eliminate a lot of code.

**Comment by leerob** [comment]
@needcaffeine That's nice! But it wouldn't match the theme of this starter. We will continue with Tailwind here.

**Comment by needcaffeine** [comment]
supabase/ui does use Tailwind, but at the moment I'm not seeing how to override the supplied theme, so perhaps you're right.

**Comment by needcaffeine** [comment]
@leerob supabase/ui uses Tailwind as well, but at the moment I'm not seeing how to override the supplied theme, so perhaps you're right to stick with this.

**Comment by needcaffeine** [comment]
@leerob Why do you think the submit button should not be disabled on the signin page?
