### ISSUE TITLE
Question about raw_user_meta_data

### ISSUE THREAD

**Issue by sarukuku** [vercel/nextjs-subscription-payments#49]
What's the purpose of copying the `raw_user_meta_data` column value to `full_name` and `avatar_url`? Couldn't these be set just to f.ex. an empty string? Is this just a leftover or does do you do this for a reason?
https://github.com/vercel/nextjs-subscription-payments/blob/767eb938e541c635489703a5d8921b6e12aceb20/schema.sql#L26

**Comment by thorwebdev** [comment]
This function is triggered when a new user is added to the auth schema (sign up or sign in via OAuth) and copies the name and avatar URL that we get from the OAuth provider (e.g. GitHub; Google; etc) to our public users table. You can find some docs about it here: https://supabase.io/docs/guides/auth#create-a-publicusers-table

**Comment by sarukuku** [comment]
Gotya, thanks for the clarification. I think this is something that should be documented by Supabase.
