### ISSUE TITLE
Is stripe sync with the database happening on the front end?

### ISSUE THREAD

**Issue by tawjaw** [vercel/nextjs-subscription-payments#51]
Hello
I'm trying to understand how the sync is automatically happening between stripe and supabase.

As I understood we have a webhook to stripe. So when a change is happening from stripe, we are handling the change and updating the database.

But isn't this webhook connection happening from the front end?

In other words, is there a chance for a user that goes through the payment to disconnect from the front end before the sync happens through the webhook?

In that case the user has paid but the database is not updated.

**Comment by kiwicopple** [comment]
Hey @tawjaw - all the functionality that sits in the `/api` folder is "server side", so it doesn't matter whether there is a user has a browser open.

You can read more here: https://nextjs.org/docs/api-routes/introduction

**Comment by tawjaw** [comment]
Oh I missed that in Nextjs
I'm only familiar with Vuejs

Thanks! That's great.
