### ISSUE TITLE
stipe/supabase sync problem 

### ISSUE THREAD

**Issue by tao101** [vercel/nextjs-subscription-payments#57]
there is a problem where stripe and supbase don't sync plans also when u add a new price to a product it syncs without the price which gives me this error .

**Comment by thorwebdev** [comment]
Did you follow the deploy instructions her? https://github.com/vercel/nextjs-subscription-payments#deploy-with-vercel

This leads you through the Stripe deploy integration for Vercel which will set up webhooks for you. As long as you follow that flow and only create your products and prices after the deployment has finished, the syncing will work fine.
