### ISSUE TITLE
Can't Finish Deployment: {"error":"Missing code or stripeCode."}

### ISSUE THREAD

**Issue by fullakingi** [vercel/nextjs-subscription-payments#61]
1. Click Vercel Deploy button
2. Continue until @ Install Integrations Screen and click "Install" Stripe Test Mode 
3. Follow prompts and select Stripe account, click connect
4. Wait for session to close, it does not close:

BUG VIDE --> https://www.loom.com/share/1d4e3e3aad534a33b4eabe63e1a59407

SCREENSHOT
<img width="2291" alt="Screen Shot 2021-04-14 at 4 07 34 PM" src="https://user-images.githubusercontent.com/6522361/114654554-90ee4680-9d3e-11eb-820a-08350f01fd79.png">

**Comment by fullakingi** [comment]
The demo looks awesome. Thanks guys for making this for the community.Hope you can find the bug, let me know if you need help.

**Comment by dbredvick** [comment]
Hey @fullakingi, our Stripe integration isn't working at the moment. I'm writing some README updates with instructions on how to manually configure Stripe until we get the integration fixed.

**Comment by fullakingi** [comment]
It's an awesome repo. Really appreciate your time and making this for the community!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by leerob** [comment]
Closing this out since the Stripe integration has been changed to instead recommend the steps in the README 👍
