### ISSUE TITLE
quantity

### ISSUE THREAD

**Issue by sroussey** [vercel/nextjs-subscription-payments#62]
`const subscription = await stripe.subscriptions.retrieve(...)` returns a subscription which does not have quantity. Guessing the relevant line should instead be: `quantity: subscription.items.data[0].quantity`

**Comment by sroussey** [comment]
BTW: converting to typescript shows these kinds of issues.

**Comment by snax4a** [comment]
> BTW: converting to typescript shows these kinds of issues.

Have you maybe converted this to typescript? I would like to have a typescript version

**Comment by perryraskin** [comment]
I believe #86 takes care of TypeScript conversion

**Comment by leerob** [comment]
Yep, I believe this is fixed now with the TS conversion 😄 I can reopen if not.
