### ISSUE TITLE
Stripe webhook failing

### ISSUE THREAD

**Issue by alaq** [vercel/nextjs-subscription-payments#64]
When I'm adding a new product on Stripe, the webhook hits my API route, but gives me the following error:

`❌ Error message: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing`

Has anyone else encountered this?

**Comment by thorwebdev** [comment]
@alaq this is likely due to an incorrect webhook secret env var (https://github.com/vercel/nextjs-subscription-payments/blob/main/.env.local.example#L9) Can you double check that you've set that correctly? If you've deployed via the deploy button in the README, then this should have been automatically set.

**Comment by alaq** [comment]
Thank you for your response @thorwebdev!

I  re-deployed once more via the deploy button in the README, to have a clean slate. After the completing the wizard I went to check the environment variables on Vercel.

I noticed that `STRIPE_WEBHOOK_SECRET` was indicating me to run `stripe --listen` (see screenshot below), which I did (`./stripe listen --forward-to=localhost:3000/api/webhooks` to be precise) and obtained the secret.

![Screen Shot 2021-04-28 at 8 19 12 PM](https://user-images.githubusercontent.com/1746118/116489684-87e39600-a863-11eb-9041-b0ae02080b02.png)

Same thing for the `SUPABASE_SERVICE_ROLE_KEY` which I retrieved from Supabase's dashboard.

After that I created my first product but got the same error. I went to the webhook on the Stripe dashboard and noticed that the secret was different, so I copy/pasted the one from the Stripe dashboard and finally re-sent the webhook, which failed again. I also tried re-deploying to see if it would update the secrets, but there was no difference.

It seems to be a me problem here, so there must be something I'm doing wrong?
Before updating these environment variables, I have tried not touching anything and running the webhook, which didn't work either.

**Comment by thorwebdev** [comment]
Stripe listen is only for local development. You can actually see that the secret was correctly set up for preview and production mode:
![image](https://user-images.githubusercontent.com/5748289/116501941-bf465700-a8e4-11eb-829e-09db6e615a3a.png)

To run this locally, you will need to first pull the env vars from vercel: https://github.com/vercel/nextjs-subscription-payments#setting-up-the-env-vars-locally and then set the missing secrets in your `.env.local` file.

But your preview and production webhook should be working. What do you see in your Stripe account under https://dashboard.stripe.com/test/webhooks? It should look something like this:
![image](https://user-images.githubusercontent.com/5748289/116502142-48f62480-a8e5-11eb-859b-8abc55d569fb.png)

And when you click on your webhook endpoint, you should see 
![image](https://user-images.githubusercontent.com/5748289/116502166-60351200-a8e5-11eb-9ef4-6964700f7fad.png)

**Comment by alaq** [comment]
I've only been using `stripe listen` to try to debug this.

Unfortunately it has never worked on the production environment. I have gone through the installation process a few times.

![Screen Shot 2021-04-29 at 1 11 48 AM](https://user-images.githubusercontent.com/1746118/116505101-11a55a80-a888-11eb-97e8-2d8aafcfce72.png)
![Screen Shot 2021-04-29 at 1 13 30 AM](https://user-images.githubusercontent.com/1746118/116505137-22ee6700-a888-11eb-945a-41143f0c8bdc.png)

**Comment by alaq** [comment]
I just re-ran everything from scratch, like the previous times, but I deleted all my Stripe accounts. This time it worked! No hiccup, this is fantastic. Thank you for your help @thorwebdev!

**Comment by belikebrahma** [comment]
anything on this?
