### ISSUE TITLE
Could you add the supabase table schema to the README?

### ISSUE THREAD

**Issue by AWaselnuk** [vercel/nextjs-subscription-payments#65]
This is my first time implementing payments with all of these technologies and this repo is helping me out A LOT.

It would go even faster if I could see the schemas for all your supabase tables at a glance. It _seems_ like many of them are complete copies of the Stripe objects, but as a new Stripe user I don't really know what those should look like. I'm particularly interested in how you are mapping stripe customers to supabase users.

Thanks for this great resource!

**Comment by thorwebdev** [comment]
@AWaselnuk did you see https://github.com/vercel/nextjs-subscription-payments/blob/main/schema.sql ?
