### ISSUE TITLE
Prices of products only partially syncing

### ISSUE THREAD

**Issue by audreyfeldroy** [vercel/nextjs-subscription-payments#67]
First off, thanks for this wonderful and thoughtfully-written sample project! We're very grateful for it and hope this bug report helps.

@pydanny and I followed the setup instructions from the README very carefully. We ran into trouble with our prices not syncing from Stripe correctly:

* In our Stripe dashboard, we have 2 products, each with 2 prices (monthly and yearly, similar to your example)
* In our Next.js app running locally, it says "No subscription pricing plans found. Create them in your Stripe Dashboard."
* When we add `console.log(products)` to Pricing.js after line 61, we see 2 products logged. The first strangely has only 1 price, and the second correctly has 2 prices. It looks like:

```
[
  {
    id: 'prod_blahblah1',
    active: true,
    name: 'Hobby',
    description: 'All the basics for starting a new business',
    image: 'blahblah',
    metadata: {},
    prices: [ [Object] ]
  },
  {
    id: 'prod_blahblah2',
    active: true,
    name: 'Freelancer',
    description: "All the basics for starting a new business",
    image: 'blahblah',
    metadata: {},
    prices: [ [Object], [Object] ]
  }
]
```

Expanding those price array entries, we see:

* The first matches our Hobby year price 🎉 
* The Hobby month price is missing ❓ 
* The third and fourth match our Freelancer month and year prices 🎉

Troubleshooting this, some further info:

* https://dashboard.stripe.com/test/webhooks correctly lists our computer under “Devices receiving events with the Stripe CLI", last seen “Currently connected” to the correct Stripe account
* We have the same exact products and prices in test and live mode
* We're experienced at working with Stripe (we wrote/maintained a popular Stripe integration for Django years ago)

Any ideas why the monthly price object for the Hobby product isn't syncing to our local Next.js app?

Anyone else running into this?

**Comment by thorwebdev** [comment]
Thanks for the kind words and sorry for the delay. Have you tried updating the prices to trigger a new webhook event and see if that helps them sync. There can be cases, especially with Stripe CLI webhook forwarding, that events don't arrive.

**Comment by thorwebdev** [comment]
Maybe it was this? https://github.com/vercel/nextjs-subscription-payments/pull/68

I'm going to close this out for now, but please do reopen if you're still experiencing it.
