### ISSUE TITLE
Can it work without Stripe Go Live

### ISSUE THREAD

**Issue by edgarasben** [vercel/nextjs-subscription-payments#70]
I've noticed Stripe Go Live is a required plugin to deploy this to Vercel. Is it possible to deploy without connecting Stripe to Vercel?

**Comment by leerob** [comment]
Yes! We're still working on the Stripe integration 🙏

**Comment by edgarasben** [comment]
Strange, it shows me here that I must connect Stripe:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/725324/123313706-0e49ea80-d52a-11eb-81d4-af98046773f7.png">

**Comment by leerob** [comment]
Try this https://vercel.com/new/select-scope?s=https%3A%2F%2Fgithub.com%2Fvercel%2Fnextjs-subscription-payments&id=311865672&b=main&c=1

You'll have to manually hook up Stripe / Supabase, that's the part we're working to iron out.
