### ISSUE TITLE
Can't see my Stripe products on Supabase & on my site

### ISSUE THREAD

**Issue by anthonyjacquelin** [vercel/nextjs-subscription-payments#72]
I followed the ReadMe perfectly to set up the project. However, even though everything is configured on Vercel, Supabase & Stripe (with registered products), I can't see my subscriptions and I'm left with the message: "No subscription pricing plans found. Create them in your Stripe Dashboard. "

I noticed that the products are not updating from Stripe and the Webhook is not working. I have the following error message on Stripe:

Webhook Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing

Thanks for any help :)

**Comment by sam-cousins** [comment]
I'm having the same issue. When I deploy the project the webhook either isn't created in Stripe, or fails authentication and I have to retry the webhook from the stripe dashboard.

**Comment by joaogarin** [comment]
Having a similar problem I don't see any webhook created in stripe. I guess there is a way to manually add this step?

**Comment by sam-cousins** [comment]
@joaogarin I found that if you click the "Skip this form" during setup of the stripe integration, the webhook is not created.

I also discovered if you don't allow some time between supabase setup and then configuring products in Stripe - the integration will fail. I can't reproduce an exact use case.

**Comment by joaogarin** [comment]
Thank you, will try it again see if I can get a different result.

**Comment by thorwebdev** [comment]
Sorry for this. We've added some instructions on how to set up the webhooks manually: https://github.com/vercel/nextjs-subscription-payments#configure-webhook
