### ISSUE TITLE
TypeError: Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by SudoStain** [vercel/nextjs-subscription-payments#73]
103 | const priceString = new Intl.NumberFormat('en-US', {
  104 |   style: 'currency',
> 105 |   currency: price.currency,
      |                  ^
  106 |   minimumFractionDigits: 0
  107 | }).format(price.unit_amount / 100);

**Comment by asheroto** [comment]
I am having this issue as well?

**Comment by asheroto** [comment]
![image](https://user-images.githubusercontent.com/49938263/132831857-ea8a64af-10f7-47ab-a468-d15173e3e083.png)

Ran yarn, broken, then yarn update, still broken.  Latest Stripe CLI.

**Comment by scottzirkel** [comment]
Be sure to setup your products & prices before redeploying.
