### ISSUE TITLE
Pros/cons of syncing stripe data

### ISSUE THREAD

**Issue by stophecom** [vercel/nextjs-subscription-payments#75]
Hi, first of all, great sample project!

Now, while browsing the code some questions came up. 
For context, I'm currently running a small [side project](https://gitlab.com/kingchiller/scrt-link) that requires more or less the same stack. Only difference is that I use [next-auth](https://next-auth.js.org/) w/ mongoDB currently. I now think about switching to supabase to simplify things even more. 

However, I noticed a small difference between our projects. I see that you do a full sync between stripe data (products, subscriptions) and your own database. I'm wondering if this is necessary - or in other words, what are pro / cons of doing so? In comparison, I only save the stripe customer ID (and a role, after a subscription is active) and fetch products, etc. on the fly. I see the upside of having e.g. products in your own DB to not rely on the stripe API (and maybe do less requests) but is it worth the extra effort? In the end, should stripe be down, you couldn't do subscriptions anyways…

I'd be happy for your thoughts/wisdom…

**Comment by thorwebdev** [comment]
@stophecom thanks for the kind words :) 

In my personal opinion a good Stripe integration should not need to make GET requests to the Stripe API, especially not to populate data on your page, as Stripe is not really meant to be used as a DB and the retrieve data performance isn't actually that great.

For small projects however it is of course completely legitimate to do this. You should however make sure that not every page load from every user translates into a request to Stripe or you could hit API rate limiting. But if you use something like incremental static regeneration with Next.js it's unlike for that to happen (e.g. that's what I do for https://github.com/thorwebdev/pymt.online/blob/main/pages/%5Bmerchant%5D/%5Bproduct%5D/index.tsx#L119-L124)

So yah, definitely a subjective topic and not really a right/wrong answer here, but my personal philosophy is to ideally only make POST requests to Stripe ;)

**Comment by stophecom** [comment]
@thorwebdev thanks for the reply. 
Now when I think about it, you're are totally right. And I wasn't even thinking about potential API rate limits. 
Since I don't have much traffic it wasn't an issue - however, I will adapt your solution; makes much more sense :)

Thanks again.
Closing the issue.
