### ISSUE TITLE
Consider using `stripe-sync-engine`

### ISSUE THREAD

**Issue by throwaway34241** [vercel/nextjs-subscription-payments#77]
I learned that supabase is developing https://github.com/supabase/stripe-sync-engine. It seems that this could replace the code in `./utils/useDatabase.js`, is that correct?

This comment in that file might be relevant:

https://github.com/vercel/nextjs-subscription-payments/blob/857941d8d7d2160b2232d4090550c74e94064ac7/utils/useDatabase.js#L5-L7

Since this is a supabase integration, it might make sense to use that sync engine.

**Comment by thorwebdev** [comment]
@throwaway34241 https://github.com/supabase/stripe-sync-engine is build with fastify and needs to be deployed separately. It's mainly meant to sync stripe data to your Postgres DB so you can run complex analytic queries on it at a later point in time. So bit of a different use case. Does that make sense?

**Comment by leerob** [comment]
Closing this out as resolved 🙏
