### ISSUE TITLE
There is no option of `receive all events` in the Select events to send section of stripe now.

### ISSUE THREAD

**Issue by newt0** [vercel/nextjs-subscription-payments#81]
>Next, click the receive all events link in the Events to send section.

There is no option of `receive all events` in the Select events to send section of stripe.

![image](https://user-images.githubusercontent.com/56229817/132685535-5890dec8-2cf0-44bc-81e7-dd3d9a73d21a.png)

Instead, I manually checked all the events.
Is this correct?
![image](https://user-images.githubusercontent.com/56229817/132685821-a26756c3-132e-4c45-88a1-fc3876e72034.png)

**Comment by chrismendes** [comment]
Clear the "Search events" search box and you should see a checkbox immediately underneath that reads, "Select all events".

![Screenshot 2021-10-31 at 16 19 53](https://user-images.githubusercontent.com/5368648/139592839-0dbff1dd-1d2d-47e9-96cc-278ddc07968d.png)
