### ISSUE TITLE
Redeployment Failed

### ISSUE THREAD

**Issue by thomasvaeth** [vercel/nextjs-subscription-payments#83]
```
21:27:21.697 | Could not find a relationship between products and prices in the schema cache
-- | --
21:27:21.699 | Unhandled error during request: {
21:27:21.699 | hint: 'If a new foreign key between these entities was created in the database, try reloading the schema cache.',
21:27:21.700 | message: 'Could not find a relationship between products and prices in the schema cache'
21:27:21.700 | }
21:27:21.700 | Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
21:27:21.701 | undefined
21:27:21.701 | info  - Generating static pages (5/5)
21:27:21.702 | > Build error occurred
21:27:21.705 | Error: Export encountered errors on following paths:
21:27:21.705 | /
21:27:21.705 | at exportApp (/vercel/path0/node_modules/next/dist/export/index.js:30:1103)
21:27:21.706 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:27:21.706 | at async /vercel/path0/node_modules/next/dist/build/index.js:39:69
21:27:21.706 | at async /vercel/path0/node_modules/next/dist/build/tracer.js:1:525
21:27:21.748 | error Command failed with exit code 1.
21:27:21.748 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:27:21.769 | Error: Command "yarn run build" exited with 1
```

<img width="753" alt="Screen Shot 2021-09-20 at 9 32 25 PM" src="https://user-images.githubusercontent.com/10190995/134103181-d2e98ffa-3e46-4844-bbbf-01a777a31add.png">

<img width="1047" alt="Screen Shot 2021-09-20 at 9 36 02 PM" src="https://user-images.githubusercontent.com/10190995/134103247-376f8cb3-5f58-4317-add4-1bad09ba1f51.png">

I followed the README to configure Stripe, but it is not working. I get the above error when trying to redeploy. I attached additional screenshots showing that I have added the environment variables and have the Stripe webhook setup.

**Comment by SaamuelBy** [comment]
Hi @thomasvaeth, how did you fixed it ?

Many thanks

**Comment by myworldbox** [comment]
Could not find a relationship between 'products' and 'prices' in the schema cache

**Comment by sebnun** [comment]
To anyone else that lands on this after googling: I solved the issue  by restarting the server on supabase, settings => general => restart server
