### ISSUE TITLE
Actual purchase not working - any suggestions how to troubleshoot?

### ISSUE THREAD

**Issue by dstroot** [vercel/nextjs-subscription-payments#84]
My system is up and working on Vercel, I can sign in, and Stripe is setup and the products are showing up, and Supabase is getting data:

<img width="1368" alt="Screen Shot 2021-09-29 at 11 28 43 AM" src="https://user-images.githubusercontent.com/1438457/135327807-c84eae48-4c2c-462e-b099-7ed4ae27d632.png">

However if I try to subscribe I get this error:

<img width="444" alt="Screen Shot 2021-09-29 at 11 29 22 AM" src="https://user-images.githubusercontent.com/1438457/135327818-344b5cdb-3981-444d-a158-6833c86d4461.png">

Not exactly sure where to start digging.  Would love any advice/thoughts.

**Comment by thorwebdev** [comment]
Do you see any error logs in your browser dev tools console or network tab? It sounds like your checkout session is not being successfully created.

**Comment by dstroot** [comment]
@thorwebdev -

You are on the right path I think.  Console is showing a 406 error from Supabase:

<img width="831" alt="Screen Shot 2021-09-30 at 7 07 14 AM" src="https://user-images.githubusercontent.com/1438457/135471094-7f01c507-b3eb-49bd-b452-892c8a498029.png">

And if I try directly:

<img width="1057" alt="Screen Shot 2021-09-30 at 7 07 48 AM" src="https://user-images.githubusercontent.com/1438457/135471176-a7b8cae7-52ae-41fb-a76d-b7c8d802c81b.png">

But other supabase access is working?  Strange...

**Comment by dstroot** [comment]
Dumped the error I was getting back:

<img width="992" alt="Screen Shot 2021-09-30 at 11 41 57 AM" src="https://user-images.githubusercontent.com/1438457/135512685-a0b05861-1bdc-4d57-8890-7fad0810e69b.png">

Doh!  Closing this issue.
