### ISSUE TITLE
Deployment fails.

### ISSUE THREAD

**Issue by shunki-github** [vercel/nextjs-subscription-payments#88]
After setting up stripe, I try to deploy and it fails.
The error is as follows
```
Unhandled error during request: FetchError: invalid json response body at https://---.supabase.co/rest/v1/products?
```

It seems that there is a problem with the supabase setting, please let me know how to solve it.

**Comment by chrismendes** [comment]
Same problem:

`FetchError: invalid json response body at https://....supabase.co/rest/v1/products?select=*%2Cprices%28*%29&active=eq.true&prices.active=eq.true&order=metadata-%3Eindex.asc.nullslast&%22prices%22.order=unit_amount.asc.nullslast reason: Unexpected token < in JSON at position 0
    at /Users/chrismendes/Documents/Projects/Stripe/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}`

Have followed the readme file to the letter. Stripe products/prices in. Webhooks ready. Keys and environment variables done. Even cleared all test data inside Stripe account. Same error when developing locally or deploying on Vercel.

**Comment by shunki-github** [comment]
This error is more likely to occur when variables are incorrect.

However, I don't think all the variables I set in Stripe are incorrect.
It is possible that the webhook URL is different, I guess.

**Comment by SaamuelBy** [comment]
Same. Anyone have any ideas to solve it ? 

Many thanks

**Comment by JannaGilleland** [comment]
I had the same issue, but when I followed the old instructions and configured supabase manually, it worked for me. 
Here is a link to the old instructions:
https://github.com/vercel/nextjs-subscription-payments/blob/745fef89ff5b1c01115dd7161ddafd13ce330afd/README.md

**Comment by shunki-github** [comment]
> https

I adopted that method and it worked!
Thank you!

**Comment by chrismendes** [comment]
> I had the same issue, but when I followed the old instructions and configured supabase manually, it worked for me. Here is a link to the old instructions: https://github.com/vercel/nextjs-subscription-payments/blob/745fef89ff5b1c01115dd7161ddafd13ce330afd/README.md#setup

Superstar! Worked for me too. Many thanks @JannaGilleland for taking the time to help. Very much appreciated, thank you.
