### ISSUE TITLE
Convert repository to template?

### ISSUE THREAD

**Issue by RobRoseKnows** [vercel/nextjs-subscription-payments#91]
Is it possible to convert this repository from a conventional repo to a GitHub template? It provides better workflows for creating private copies.

**Comment by thorwebdev** [comment]
Sorry for the late reply. I don't have access to the repo settings anymore, so would need @leerob or someone from the Vercel team to do this.

**Comment by leerob** [comment]
Hey! I think we're going to leave this as is - thank you for the suggestion though! 😄
