### ISSUE TITLE
Supabase not saving full_name when user signs up

### ISSUE THREAD

**Issue by danidz96** [vercel/nextjs-subscription-payments#92]
Hi!
I was doing a project on my own and when trying to update the users table it gives a 404 supabase error.
I have seen that it happens to more people but I cannot see why, it seems that it is related to the policies of the table, but I have tried everything and nothing works.

Desperate I have created a new project in supabase, I have cloned this repo and executed the SQL schema, but it also gives the same error.

![image](https://user-images.githubusercontent.com/37420305/143041967-dbf3d7e1-cb2c-455f-8811-c15fbc5d4ce0.png)
![image](https://user-images.githubusercontent.com/37420305/143042001-aa8f8bae-8afd-4662-958e-cc4299f79f30.png)
![image](https://user-images.githubusercontent.com/37420305/143042084-c5effaca-c0cf-490d-8c68-af130ebcb732.png)

I also tried with Postman but returns the same error.
Maybe is a bug with supabase or something bad configured.

Update: I disabled Row Level Policy and it worked but that's not secure

Someone else happens?

**Comment by davevanhoorn** [comment]
By default the Supabase *signUp* function doesn't return a user session. Without a user session the Row Level Security will prevent any updates to the data. Supabase wants the user to confirm their email first - then it'll return a user session.

**Quick fix**
Go to your Supabase admin panel -> Authentication -> Settings and disable **Enable email confirmations**. Once disabled the signUp function returns a user session (with which you can update the data).

Read the signUp notes [here](https://supabase.com/docs/reference/javascript/auth-signup)

**Comment by danidz96** [comment]
Oh, thank you. My bad... Is my first time with supabase and I didn't realize that
