### ISSUE TITLE
I have problems with deploying my app and i added all the env vars, please help me

### ISSUE THREAD

**Issue by pavel-256** [vercel/nextjs-subscription-payments#96]
![Screenshot 2022-01-01 003810](https://user-images.githubusercontent.com/66841547/147840428-3ae324ed-b7e8-4e96-a182-49f0bad40a1a.jpg)
![Screenshot 2022-01-01 003639](https://user-images.githubusercontent.com/66841547/147840430-e3457bd3-8e3a-41d8-8d71-413641ba7b69.jpg)

**Comment by pavel-256** [comment]
I solved the problem, just added the schema.sql content to supabase manually

**Comment by myworldbox** [comment]
[](https://github.com/vercel/nextjs-subscription-payments/blob/971f8844572efcb163b00efa32261c7c479a286a/README.md#1-create-new-supabase-project)Configuration
1. Create new Supabase project
Sign up to Supabase - https://app.supabase.io/[](https://github.com/vercel/nextjs-subscription-payments/blob/971f8844572efcb163b00efa32261c7c479a286a/README.md#2-set-up-your-database-tables-and-auth-policies) and create a new project. Wait for your database to start.

2. Set up your database tables and auth policies
In your Supabase dashboard, go to the SQL editor. There, the welcome tab has a "Quick Start" section. Select the "Stripe Subscriptions" quick start (it has the same content as the [schema.sql file](https://github.com/vercel/nextjs-subscription-payments/blob/971f8844572efcb163b00efa32261c7c479a286a/schema.sql)[](https://github.com/vercel/nextjs-subscription-payments/blob/971f8844572efcb163b00efa32261c7c479a286a/README.md#optional---set-up-oauth-providers)) and hit the "RUN" button.

[Optional] - Set up OAuth providers
You can use third-party login providers like GitHub or Google. Refer to the [docs](https://supabase.io/docs/guides/auth#third-party-logins) to learn how to configure these.
