### ISSUE TITLE
Flicker on Sign In Page

### ISSUE THREAD

**Issue by techandmedia** [vercel/nextjs-subscription-payments#97]
If you already in a Sign Up page or in a Sign In page and click a Account Link the screen flickers (one time) with a Sign In Page

This happens before the user can sign in.

Reading from the code and trying to do this don't work, instead the Sign In page flashing, now it's the footer flashing
```bash
if (!user) return <>Loading...</>;
```

**Comment by EpicDevv** [comment]
did you ever figure this out

**Comment by techandmedia** [comment]
> did you ever figure this out

No, still having problem with this

**Comment by lukebussey** [comment]
It's because `user` is null for a brief moment. I'm also trying to figure this out.

**Comment by lukebussey** [comment]
I think I've managed to fix this. `supabase.auth.session()` and `supabase.auth.user()` are both synchronous so you can use them to set the initial state.

https://github.com/vercel/nextjs-subscription-payments/blob/main/utils/useUser.tsx#L38

```diff

 export const UserContextProvider = (props: any) => {
   const [userLoaded, setUserLoaded] = useState(false);
-  const [session, setSession] = useState<Session | null>(null);
-  const [user, setUser] = useState<User | null>(null);
+  const [session, setSession] = useState<Session | null>(supabase.auth.session());
+  const [user, setUser] = useState<User | null>(supabase.auth.user());
   const [userDetails, setUserDetails] = useState<UserDetails | null>(null);
```

**Comment by thorwebdev** [comment]
I'm working on an update to utilise https://github.com/supabase-community/supabase-auth-helpers/blob/main/src/nextjs/README.md which should eliminate this.
