### ISSUE TITLE
Implementing paid content page

### ISSUE THREAD

**Issue by EpicDevv** [vercel/nextjs-subscription-payments#98]
how would i go about authenticating a user and the pricing plan they purchased to then show them the content  they paid for in like a dashboard page?

**Comment by thorwebdev** [comment]
There's a couple of ways of doing this, e.g.

- You can use RLS, example here: https://github.com/vercel/nextjs-subscription-payments/blob/refactor/simple-paywall/schema.sql#L150-L159
- You can use an API route or SSR to verify their JWT, check their subscription status and then return info based on that. Here some examples of verifying the users JWT server-side: https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth#example-supabase-authentication-client--and-server-side-api-routes-and-ssr-with-auth-cookie
