### ISSUE TITLE
Any documentation about how to setup supabase manually?

### ISSUE THREAD

**Issue by futantan** [vercel/nextjs-subscription-payments#99]
I have an existing project and want to use supabase & stripe like this project does.
Is there any document about what happened behind the DEPLOY button?

**Comment by leerob** [comment]
The deploy button here (+ the Supabase integration) connects your accounts together. To manually connect your accounts, you need to add your connection information from Supabase as [Environment Variables](https://vercel.com/docs/concepts/projects/environment-variables) inside the Vercel dashboard.

**Comment by futantan** [comment]
Apart from the environment variables, the supabase setup some tables and webhooks in the background, that the most important missing part

**Comment by thorwebdev** [comment]
You can find these steps in a previous version of the README: https://github.com/vercel/nextjs-subscription-payments/blob/971f8844572efcb163b00efa32261c7c479a286a/README.md#configuration

**Comment by futantan** [comment]
Thank you! @thorwebdev 
This is exactly what I'm looking for!
